# Site settings
title: My Journey to learn on Learn
header-img: img/home-bg.png
email: admin@bigrocketgames.com
copyright_name: bigrocketgames
description: > # this means to ignore newlines until "baseurl:"
  An inside look at my online learning journey.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bigrocketgames
learn_profile: bigrocketgames
email_username: admin@bigrocketgames.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
